### ISSUE TITLE
PHP 8.1 Compatability

### ISSUE THREAD

**Issue by neilherbertuk** [vanderbilt-redcap/advanced_import#4]
We've just been upgrading the infrastructure for one of our test instances of REDCap and it seems that this external module is not compatible with PHP 8.0 or PHP 8.1 (PHP 7 went EOL Monday 28th Nov 2022). I've tried different versions of REDCap and consistently get this issue from `12.5.9` (the earliest version I've tried it with) through to `13.0.1`. 

```
[This message was automatically generated by REDCap]

Cron job 'advanced_import_check_jobs' failed for External Module 'advanced_import'.

Exception: TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/app/current/redcap/modules/advanced_import_v1.9.3/AdvancedImport.php:291
Stack trace:
#0 /var/app/current/redcap/modules/advanced_import_v1.9.3/AdvancedImport.php(291): count(NULL)
#1 /var/app/current/redcap/redcap_v13.0.1/ExternalModules/classes/ExternalModules.php(6289): Vanderbilt\AdvancedImport\AdvancedImport->cron_checkJobs(Array)
#2 /var/app/current/redcap/redcap_v13.0.1/Classes/Cron.php(319): ExternalModules\ExternalModules::callCronMethod('5', 'advanced_import...')
#3 /var/app/current/redcap/redcap_v13.0.1/cron.php(23): Cron->execute()
#4 /var/app/current/redcap/cron.php(9): include('/var/app/curren...')
#5 {main}

Server: removed
User: SYSTEM
Module Name: Advanced Import/Export (advanced_import)
Module Author(s): francesco.delacqua@vumc.org
Run Time: 0 seconds
```

The error refers to line `291` of `AdvancedImport.php` https://github.com/vanderbilt-redcap/advanced_import/blob/master/AdvancedImport.php#L291

```
288: function cron_checkJobs($cronInfo)
289: {
290:        $stuckJobs = $this->stopStuckJobs();
291:        $totalStuck = count($stuckJobs);
292:        $messages = ['All jobs have been checked.'];
293:        if($totalStuck>=1) {
```

Line 290 ` $stuckJobs = $this->stopStuckJobs();` is always null as the `stopStuckJobs();` method does not have a return statement.

https://github.com/vanderbilt-redcap/advanced_import/blob/master/AdvancedImport.php#L264
```
252:    private function stopStuckJobs() {
253:        $queue = new Queue();
         ...
263:        }
264:        $stuckJobs;
265:    }
```

Line 264, the last line of `stopStuckJobs` doesn't return anything. I've manually added the `return` keyword to this line and no longer get the error. It also doesn't look like `$stuckJobs` is actually being set apart from it being set to an empty array.

I don't know if there are any other compatibility issues as I do not know enough about this external module to test it.

**Comment by neilherbertuk** [comment]
@bi0nd0 any chance you can take a look at this?

**Comment by neilherbertuk** [comment]
@bi0nd0

**Comment by neilherbertuk** [comment]
This seems to have been resolved with the recent updates.
